language: node_js
node_js:
  - "10"
before_install: 
   
before_script:
    - npm install
script:
  - npm run build:ci
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run test:sauce ; fi 
after_failure:
  - ls

addons:
  sauce_connect:true
env:
  global:
    - secure: "OlXY+5ef6JX3kgeo0DddJk4nuCljfF2k5Z3nV90BWI6tFHT9TxJUii3FTiDcNngNbklaEcsHtSVFkMIGK80hEm5ZXkekEQX7l/TY38KgaA/szPUGJRFrLVMd4yib0YFOIqG8Dsagid0cbJvHI6trjie89lyjoG36oY9DIPEkQLzLPh+P14+zCRGMPxFzka631iAqv0GWCam+Wx2l7BqlcqTcI0JmGJnwb0A3mWPfZ3Y67amQ4jEnZHxlN/FcMHDW5W/rN3uyFr2+iTfCDfu+06+2PklP1wFsVgOuEMNcyYvS7OAI511NnkRbeYjOE/vUZmJCnSAZABHZ9JhLmIM2grFZHfLNqgkNqweE3y4znrsmrPzmzwS3bSkPfCBeR7Sv7yGHJ2itvL6X/ie96bshgcbAOHkk3K3CMwHMfug0A/L/4yYttXTQ1Ic/NeuNxwz2jRW05r6cTmm/nDUxWW5vOVBt6cXZyzwnxM7Cyqk9WDKNzJ8mNj8o4Y8XAsww7gTzYqysFD80+gD/LesCh2buu5zCGUIZXGhjC+A2T3GCZFiI7AM26vkhMmhIXuvWMlkvTXg8Yt5E7+5q0Wtsjn2ec8ISkaK4hra0Nstvhgbvp7vHj6TeFksRsNshE9Tm+ghrEZ1ngH5y26cL4FQ8pjlX1/9Nh6lvjauUsWTjd5WmM4g="
    - secure: "RH2a/vmZa6bUOdSsScjks1qrBgHS0YmuPKRGch5EfDIrVBAv20qiVC62heHDLWLNGeo8Xv9Sjg1bWDYx9Q4FJHQRfgyotV6w/FJDG9LRxvNpXJsYRpifSIMnTv5xfZ/RKWG0DHNojOybU2OM3sdIDcSndKVQ8SbdINAFPQb1KSm07ICGF0RW10Xz+HaYoNp6M+AIEEeCi9dM6tp3Xl6KwAOhjphotToFbg3+j2ngirfWGupCG6DTVYXwpphhACyPdNXtktx8uZYnx+DuyQw6vIq8zwP8oakD9egE66y0Sur+azyu34jhOZCSGi0kFg4iNHZpKZ3RKnFVtNe58eRuAx4F7G1DmCWs4XjBG881jM64u9m06PruvPoFllmG2vbhhkvqnfo7fF1uM7NbB5iGrAYd5RnbValFqi6EF+QlrR5jdTY3NCM5NLiFfuSnVKOgNBm8Q/fpyuJalGlh8dMm4/iwqV7VKF52XjJ7n0oIAutUYIvxAcxQmqnPSYSs4YvQOSLijJrYoSLirZbxzJ4r0mXcUN6/sTrz+1YCwX0wEeijuK0jjRdxewgIQxRuku+au3kVIziNmPwLawmAPDsBDdykfnhdLltRjvdWNe6toMF8CnOeN27lnMBbtLyNDcpvYX4LB5tXXizkC3pjCLUUFxBNznwUTW/RdxQ4cT2jfFc="
    